
// ============================== ALL ARTIST
export const GET_ARTIST_REQUEST = "GET_ARTIST_REQUEST";
export const GET_ARTIST_FAIL = "GET_ARTIST_FAIL";
export const GET_ARTIST_SUCCESS = "GET_ARTIST_SUCCESS";
export const GET_ARTIST_ERROR = "GET_ARTIST_ERROR";

// ============================== GET SPECIFIC ARTIST
export const GET_SPECIFIC_ARTIST_REQUEST = "GET_SPECIFIC_ARTIST_REQUEST";
export const GET_SPECIFIC_ARTIST_FAIL = "GET_SPECIFIC_PARENT_CATEGORY_FAIL";
export const GET_SPECIFIC_ARTIST_SUCCESS = "GET_SPECIFIC_ARTIST_SUCCESS";
export const GET_SPECIFIC_ARTIST_ERROR = "GET_SPECIFIC_ARTIST_ERROR";

// ============================== CREATE ARTIST
export const ARTIST_CREATE_REQUEST = "ARTIST_CREATE_REQUEST";
export const ARTIST_CREATE_FAIL = "ARTIST_CREATE_FAIL";
export const ARTIST_CREATE_ERROR = "ARTIST_CREATE_ERROR";
export const ARTIST_CREATE_SUCCESS = "ARTIST_CREATE_SUCCESS";

// ============================== UPDATE ARTIST
export const ARTIST_UPDATE_REQUEST = "ARTIST_UPDATE_REQUEST";
export const ARTIST_UPDATE_FAIL = "ARTIST_UPDATE_FAIL";
export const ARTIST_UPDATE_ERROR = "ARTIST_UPDATE_ERROR";
export const ARTIST_UPDATE_SUCCESS = "ARTIST_UPDATE_SUCCESS";


// ============================== DELETE ARTIST
export const ARTIST_DELETE_REQUEST = "ARTIST_DELETE_REQUEST";
export const ARTIST_DELETE_FAIL = "ARTIST_DELETE_FAIL";
export const ARTIST_DELETE_ERROR = "ARTIST_DELETE_ERROR";
export const ARTIST_DELETE_SUCCESS = "ARTIST_DELETE_SUCCESS";
